# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiSMsignup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_SafeMoneySignup(QMainWindow):
    def __init__(self):
        super(Ui_SafeMoneySignup, self).__init__()
        self.setupUi(self)

    def setupUi(self, SafeMoneySignup):
        SafeMoneySignup.setObjectName("SafeMoneySignup")
        SafeMoneySignup.resize(400, 450)
        font = QtGui.QFont()
        font.setPointSize(10)
        SafeMoneySignup.setFont(font)
        self.author_label = QtWidgets.QLabel(SafeMoneySignup)
        self.author_label.setGeometry(QtCore.QRect(9, 425, 128, 16))
        self.author_label.setObjectName("author_label")
        self.programname_label = QtWidgets.QLabel(SafeMoneySignup)
        self.programname_label.setGeometry(QtCore.QRect(9, 35, 382, 23))
        self.programname_label.setMinimumSize(QtCore.QSize(382, 0))
        self.programname_label.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.programname_label.setFont(font)
        self.programname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.programname_label.setObjectName("programname_label")
        self.label = QtWidgets.QLabel(SafeMoneySignup)
        self.label.setGeometry(QtCore.QRect(9, 89, 38, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SafeMoneySignup)
        self.label_2.setGeometry(QtCore.QRect(9, 139, 35, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(SafeMoneySignup)
        self.label_3.setGeometry(QtCore.QRect(9, 189, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(SafeMoneySignup)
        self.label_4.setGeometry(QtCore.QRect(9, 239, 104, 16))
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(SafeMoneySignup)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 345, 381, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.signup_button = QtWidgets.QPushButton(self.layoutWidget)
        self.signup_button.setObjectName("signup_button")
        self.horizontalLayout.addWidget(self.signup_button)
        self.back_button = QtWidgets.QPushButton(self.layoutWidget)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        self.label_5 = QtWidgets.QLabel(SafeMoneySignup)
        self.label_5.setGeometry(QtCore.QRect(9, 289, 79, 16))
        self.label_5.setObjectName("label_5")
        self.currencyButton = QtWidgets.QToolButton(SafeMoneySignup)
        self.currencyButton.setGeometry(QtCore.QRect(369, 311, 22, 28))
        self.currencyButton.setMinimumSize(QtCore.QSize(0, 28))
        self.currencyButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.currencyButton.setAcceptDrops(False)
        self.currencyButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.currencyButton.setObjectName("currencyButton")
        self.name = QtWidgets.QLineEdit(SafeMoneySignup)
        self.name.setGeometry(QtCore.QRect(9, 111, 381, 22))
        self.name.setObjectName("name")
        self.login = QtWidgets.QLineEdit(SafeMoneySignup)
        self.login.setGeometry(QtCore.QRect(9, 161, 381, 22))
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(SafeMoneySignup)
        self.password.setGeometry(QtCore.QRect(9, 211, 381, 22))
        self.password.setObjectName("password")
        self.repeatpassword = QtWidgets.QLineEdit(SafeMoneySignup)
        self.repeatpassword.setGeometry(QtCore.QRect(9, 261, 381, 22))
        self.repeatpassword.setObjectName("repeatpassword")
        self.balance = QtWidgets.QLineEdit(SafeMoneySignup)
        self.balance.setGeometry(QtCore.QRect(9, 314, 351, 22))
        self.balance.setObjectName("balance")
        self.status_label = QtWidgets.QLabel(SafeMoneySignup)
        self.status_label.setGeometry(QtCore.QRect(10, 380, 381, 16))
        self.status_label.setStyleSheet("color : red;")
        self.status_label.setFrameShape(QtWidgets.QFrame.NoFrame)

        self.retranslateUi(SafeMoneySignup)
        QtCore.QMetaObject.connectSlotsByName(SafeMoneySignup)

    def retranslateUi(self, SafeMoneySignup):
        _translate = QtCore.QCoreApplication.translate
        SafeMoneySignup.setWindowTitle(_translate("SafeMoneySignup", "SafeMoney - sign up"))
        self.author_label.setText(_translate("SafeMoneySignup", "Anton Schcukin - 2023"))
        self.programname_label.setText(_translate("SafeMoneySignup", "SafeMoney"))
        self.label.setText(_translate("SafeMoneySignup", "Name:"))
        self.label_2.setText(_translate("SafeMoneySignup", "Login:"))
        self.label_3.setText(_translate("SafeMoneySignup", "Password:"))
        self.label_4.setText(_translate("SafeMoneySignup", "Repeat password:"))
        self.signup_button.setText(_translate("SafeMoneySignup", "Sign up"))
        self.back_button.setText(_translate("SafeMoneySignup", "Back to register"))
        self.label_5.setText(_translate("SafeMoneySignup", "Your balance:"))
        self.currencyButton.setText(_translate("SafeMoneySignup", "₽"))
