# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiSMlogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_SafeMoneyLogin(QMainWindow):
    def __init__(self):
        super(Ui_SafeMoneyLogin, self).__init__()
        self.setupUi(self)

    def setupUi(self, SafeMoneyLogin):
        SafeMoneyLogin.setObjectName("SafeMoneyLogin")
        SafeMoneyLogin.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SafeMoneyLogin.sizePolicy().hasHeightForWidth())
        SafeMoneyLogin.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(SafeMoneyLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.author_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.author_label.setFont(font)
        self.author_label.setObjectName("author_label")
        self.gridLayout.addWidget(self.author_label, 6, 0, 1, 1)
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.programname_label = QtWidgets.QLabel(self.centralwidget)
        self.programname_label.setMinimumSize(QtCore.QSize(382, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.programname_label.setFont(font)
        self.programname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.programname_label.setObjectName("programname_label")
        self.gridLayout.addWidget(self.programname_label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 4, 0, 1, 1)
        SafeMoneyLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(SafeMoneyLogin)
        QtCore.QMetaObject.connectSlotsByName(SafeMoneyLogin)

    def retranslateUi(self, SafeMoneyLogin):
        _translate = QtCore.QCoreApplication.translate
        SafeMoneyLogin.setWindowTitle(_translate("SafeMoneyLogin", "SafeMoney - log in"))
        self.login_button.setText(_translate("SafeMoneyLogin", "Log in"))
        self.back_button.setText(_translate("SafeMoneyLogin", "Back to register"))
        self.author_label.setText(_translate("SafeMoneyLogin", "Anton Schcukin - 2023"))
        self.label_3.setText(_translate("SafeMoneyLogin", "Password:"))
        self.programname_label.setText(_translate("SafeMoneyLogin", "SafeMoney"))
        self.label_2.setText(_translate("SafeMoneyLogin", "Email: "))
