# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiSMreg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget


class Ui_SafeMoneyreg(QMainWindow):
    def __init__(self):
        super(Ui_SafeMoneyreg, self).__init__()
        self.setupUi(self)

    def setupUi(self, SafeMoneyreg):
        SafeMoneyreg.setObjectName("SafeMoneyreg")
        SafeMoneyreg.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(9)
        SafeMoneyreg.setFont(font)
        self.programname_label = QtWidgets.QLabel(SafeMoneyreg)
        self.programname_label.setGeometry(QtCore.QRect(9, 9, 382, 100))
        self.programname_label.setMinimumSize(QtCore.QSize(382, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.programname_label.setFont(font)
        self.programname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.programname_label.setObjectName("programname_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(SafeMoneyreg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 115, 382, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.login_button.setMinimumSize(QtCore.QSize(187, 23))
        self.login_button.setMaximumSize(QtCore.QSize(187, 23))
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        self.signup_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.signup_button.setMinimumSize(QtCore.QSize(187, 23))
        self.signup_button.setMaximumSize(QtCore.QSize(187, 23))
        self.signup_button.setObjectName("signup_button")
        self.horizontalLayout.addWidget(self.signup_button)
        self.forgetpassword_button = QtWidgets.QPushButton(SafeMoneyreg)
        self.forgetpassword_button.setEnabled(False)
        self.forgetpassword_button.setGeometry(QtCore.QRect(9, 146, 382, 23))
        self.forgetpassword_button.setMinimumSize(QtCore.QSize(382, 23))
        self.forgetpassword_button.setMaximumSize(QtCore.QSize(382, 23))
        self.forgetpassword_button.setObjectName("forgetpassword_button")
        self.author_label = QtWidgets.QLabel(SafeMoneyreg)
        self.author_label.setGeometry(QtCore.QRect(9, 277, 126, 16))
        self.author_label.setObjectName("author_label")
        self.retranslateUi(SafeMoneyreg)
        QtCore.QMetaObject.connectSlotsByName(SafeMoneyreg)

    def retranslateUi(self, SafeMoneyreg):
        _translate = QtCore.QCoreApplication.translate
        SafeMoneyreg.setWindowTitle(_translate("SafeMoneyreg", "SafeMoney - register"))
        self.programname_label.setText(_translate("SafeMoneyreg", "SafeMoney"))
        self.login_button.setText(_translate("SafeMoneyreg", "Log in"))
        self.signup_button.setText(_translate("SafeMoneyreg", "Sign up"))
        self.forgetpassword_button.setText(_translate("SafeMoneyreg", "Forget password?"))
        self.author_label.setText(_translate("SafeMoneyreg", "Anton Schcukin - 2023"))
